### ISSUE TITLE
The digest file is invalid

### ISSUE THREAD

**Issue by singhGurpreetHsc** [threerings/getdown#115]
Hi,

I am going to create digest file using java -jar command. the alert window is showing the error "The digest file is invalid".

My Getdown.txt file is:

# The URL from which the client is downloaded
appbase = http://app.com/app

# UI Configuration
ui.name = My Application

# Application jar files
code = application.jar

# The main entry point for the application
class = com.threerings.getdown.tools

Please let me know if there is any other issue in this.

**Comment by samskivert** [comment]
I'm not sure exactly what your problem is, nor how to help. Are you saying that you're trying to create a digest.txt file for your app? If so, you cannot run `java -jar getdown.jar appdir` because the main class in getdown.jar is the Getdown app itself, not the digester tool.

To create a digest, you should run:

```
java -classpath getdown-X.Y.jar com.threerings.getdown.tools.Digester myapp
```

As described here: https://github.com/threerings/getdown/wiki/Quick-Start
