### ISSUE TITLE
Desktop Shortcuts/Link

### ISSUE THREAD

**Issue by vgropp** [threerings/getdown#141]
Hi,

as we try to eliminate an installer with getdown, we think about the posibilty to let getdown create a shortcut i.e. on the Windows Desktop to start getdown for this application the next time.

Does this fit to the getdown design goals and did you already think about this? I know creating a shortcut in windows is not an easy task. That's why i'm asking before we try to implement something already solved or something that doesn't fit to getdown design goals.

Volker

**Comment by samskivert** [comment]
Traditionally, we have left the job of creating desktop shortcuts to the per-platform installer that one uses to "install" Getdown, a JVM, and the basic metadata needed to allow Getdown to install the rest of the application.

I'm not opposed to the idea of Getdown creating the desktop shortcuts for the application, but it seems of little value to create and maintain code for this one small piece of the puzzle. It's also not platform agnostic. Windows uses desktop shortcut files. The macOS doesn't use separate files, apps can simply be dragged to the dock. I have no idea what Linux desktop managers use these days for app shortcuts. Long ago, they used a metadata file in a directory, somewhat like Windows, but that has almost certainly changed.

Instead of adding a half-baked and doomed to never be well supported feature to Getdown, I'd rather you just added code to your own app that creates these shortcut files exactly where you need them. You seem to only care about deploying to Windows, so you can focus just on that use case. You have a very specific use case which you can probably address with simple straightforward code. Anything that goes into Getdown needs to be general purpose, ideally work across all platforms, well documented, robust, etc. And someone has to maintain it as operating systems and standards change over the years.
