### ISSUE TITLE
licensing to use with our commercial products

### ISSUE THREAD

**Issue by sreerama-naga** [threerings/getdown#143]
Hi,

I see **getdown** is open source frame work.
Had few below questions related to licensing to use, 
1) is it fine if we use in our commercial product?
2) is it fine if we change any code (if required for us to do) and use in our commercial product?

thank you!

**Comment by samskivert** [comment]
Getdown is BSD licensed. I am not a lawyer, but I take that to mean that it is OK to use in your commercial product, and it is OK to modify it prior to using it in your commercial product, and you are not required to contribute your modifications back to the original project.

If you were to redistribute the source code of Getdown (with or without modifications), you would be required to include the `LICENSE` file from the Getdown repository with your redistributed source code.

Technically, the BSD license also requires that you include the information in the `LICENSE` if you redistribute Getdown in binary form. It was not my intention in the selection of the BSD license that anyone who uses Getdown to distribute their application (commercial or otherwise) be required to have some sort of "License info" dialog in their app that includes the Getdown license information. So that is not necessary.

The two things that I care about are:

1. If you do redistribute the source code to a customized Getdown, that you include the `LICENSE` information.

2. The Getdown authors are in no way liable for whatever happens as a result of you using the Getdown source or binary in your application.
