### ISSUE TITLE
Does getdown work with HTTPS ?

### ISSUE THREAD

**Issue by sreerama-naga** [threerings/getdown#146]
Hi,

1) It is mentioned in the doc it works with HTTP. Does this work well with HTTPS as well ?
2) also does it work if the webserver is in FIPS enabled mode ?

thank you!

**Comment by samskivert** [comment]
Getdown does work with HTTPS in the exact same way it works with HTTP. It simply uses Java's internal HTTP APIs which support both HTTPS and HTTP.

I have no idea whether it works with FIPS because I don't know what that is, but if Java supports it, then Getdown supports it. Getdown uses Java's standard `java.net` APIs to open HTTP/S connections, it does not reimplement that entire protocol internally or anything crazy like that.
