### ISSUE TITLE
Allow getdown to open more than one instance of the app

### ISSUE THREAD

**Issue by marianpavel** [threerings/getdown#36]
Hi, Is there a way how can I configure getdown to allow more than 1 instance of my app ?

**Comment by samskivert** [comment]
I'm not sure what you mean. You can run your app using Getdown and then run it again and the previous version will still be running. You can't run two copies in rapid succession because while Getdown is checking whether it needs to update your app, it will refuse to allow another copy of Getdown to run, but once the first one is done with its checks, you can run another one again.

But maybe this isn't what you mean. Can you explain what you're trying to do in more detail?
