### ISSUE TITLE
Using resources from different servers

### ISSUE THREAD

**Issue by MystyxMac** [threerings/getdown#50]
I have a application that uses resources (jars) on a server (in our maintenance). These jars are updated every 3 months or so. I don't want to download these jars and update the getdown app every time. 

Is it possible to let getdown download these resources and put it on the classpath?
I believe it worked with Java Web Start.

Other approaches I can use to fix this problem?

**Comment by samskivert** [comment]
That's pretty far outside the design goals of Getdown. It is designed to download a package of code and data to a user's local machine and run the app from there. It doesn't download from multiple servers and it doesn't handle arbitrary files that are not part of the Getdown manifest. It needs to know the MD5 hash of all the files that are part of the app package so that it can validate them. Pulling random jars off of a server would not really work with that process.

You can have your app download those jars and then create a classloader that uses the boot class loader (which will have all the jars Getdown installed) along with the jars your app downloaded, and then run the rest of your app using that classloader. Then you can decide how you want to do things. You can always access them over the network if you have a reliable internet connection, or you can download and cache them locally, then check every time the app starts up to see if they've changed.
