### ISSUE TITLE
get down 1.6 starting with an appbase with empty appdir fails on digest

### ISSUE THREAD

**Issue by soapyfrog** [threerings/getdown#75]
Using get down 1.6 on an empty appdir with `-Dappbase=xxx` or an appdir with just a `getdown.txt` with `appase=xxx` fails because it can't find `digest2.txt`

Eg, in empty directory:
```
java -Dappbase=http://xxx/yyy -jar /lib/getdown-1.6.jar .
```

popup error saying:

```
The application has failed to launch due to missing resource:
http://xxx/yyy/digest.txt
```

As I'm using getdown 1.6, the digest is version 2 and so the digest file is `digest2.txt` not `digest.txt` and I don't think this should be an error.

**Comment by soapyfrog** [comment]
Stack trace in launcher:
```
2016/11/29 08:43:52:380 WARNING n.a: getdown() failed.
java.io.FileNotFoundException: http://xxx/yyy/digest.txt
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
        at com.threerings.getdown.data.Application.downloadFile(Unknown Source)
        at com.threerings.getdown.data.Application.downloadControlFile(Unknown Source)
        at com.threerings.getdown.data.Application.downloadDigestFiles(Unknown Source)
        at com.threerings.getdown.data.Application.verifyMetadata(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
```

**Comment by soapyfrog** [comment]
It seems to work if I create digests for both versions 1 and 2, but that feels redundant.

**Comment by samskivert** [comment]
So you have a completely new project with users that have never had an older version of Getdown installed, so you want to be able to deploy your project with only digest2.txt? Because if anyone has ever run your project with a getdown.jar that uses digest.txt, you need to continue to ship a digest.txt file for as long as you want those users to be able to continue to function.

If they haven't run your project for a year, and then decide to give it a shot, but you stopped shipping digest.txt files, then their old installation will be unable to upgrade because it needs to see a digest.txt file.

So yes, if this is a completely new app that has never had users, you do have to keep this vestigial digest.txt file around, which is annoying, but I didn't have time to do the extra work to make Getdown cope with not having a digest.txt file. I'll try to get to that at some point, but it's going to require a bunch of configuration changes so that you can specify to the digester not to create digest.txt and then probably a way to specify to Getdown that you're a 'second generation' app and blah blah.

**Comment by soapyfrog** [comment]
Yes, the case we have is someone using Getdown for the very first time.

I work around it at the moment by generating both v1 and 2 digests and that seems to make things go ok.
