### ISSUE TITLE
Version verification fails silently in case of non 200 (ok) http response

### ISSUE THREAD

**Issue by bugy** [threerings/getdown#79]
If application is version based, then the request is made to http server to read updated getdown.txt file. And then response result is parsed to read the version config from there (i.e. version=xxx line).

However, a server can reply with any non-OK response (e.g. 301, moved permanently). In this case the body will contain some error text and getdown will try to find version=xxx line there, which obviously won't be there. So it will skip version check.

I think such case can be treated as an exception and at least warning could be logged.

**Comment by samskivert** [comment]
In my tests, when a server returns a non-200 error code, an exception *is* thrown. If you're talking about the code that checks a `latest` URL to see if the version in that URL is newer than the installed version, that code intentionally does not fail to launch the application if it cannot check for a newer version.

When an exception is thrown, it logs a warning, just as you suggest:

```java
                try {
                    in = ConnectionUtil.open(_latest).getInputStream();
                    BufferedReader bin = new BufferedReader(new InputStreamReader(in));
                    for (String[] pair : ConfigUtil.parsePairs(bin, false, false)) {
                        if (pair[0].equals("version")) {
                            _targetVersion = Math.max(Long.parseLong(pair[1]), _targetVersion);
                            if (fileVersion != -1 && _targetVersion > fileVersion) {
                                // replace the file with the newest version
                                out = new PrintStream(new FileOutputStream(vfile));
                                out.println(_targetVersion);
                            }
                            break;
                        }
                    }
                } catch (Exception e) {
                    log.warning("Unable to retrieve version from latest config file.", e);
                } finally {
                    StreamUtil.close(in);
                    StreamUtil.close(out);
                }
```

Perhaps on some JVMs a call to getInputStream on an HttpURLConnection that has returned a non-200 response code does not throw an exception? I have not seen that to be the case, and it is not the case in my testing today. This code has been in deployment on tens or hundreds of thousands of computers for over a decade. It's not impossible that this has gone unnoticed in that time, but it would be surprising.

It should be noted as well that using `latest` is purely a "best effort" mechanism to update the application. That's why we just log a warning and continue if the attempt to check the version fails. This mechanism should be used when updating your application is not critical to its functioning.

We didn't even have this mechanism when we originally created Getdown, because we made Getdown to ship apps where being on the correct version *was* critical to functioning (complex client/server apps where the client had to be in sync with the server).

For cases where updating is critical, you should have your application itself detect when it is out of date (either because it connected to a server and the server told it that its version was old and what the new version is, or via whatever means you have of knowing that your app is out of date). Then your app should create a version.txt file with the new target version and relaunch itself (all of which is easy to do with `LaunchUtil.updateVersionAndRelaunch`).

**Comment by bugy** [comment]
Hi samskivert, thank you for the reply.

May be the issue happens only on non-fatal responses (like moved permanently in our case, because it's clear how such problem should be solved). 

Regarding the skip of the update, if we couldn't read the version, it's fine. The problem in our case is that the problem occurs absolutely silently. As exception is not thrown for us, the warning is not logged.

I'll double-check next week, why and in which response codes HttpURLConnection throws an exception and report the results in this issues.
